using MessagePack;

namespace TestConvertJson.Models.Stock6GModels
{
    [MessagePackObject(true)]
    public class DVX
    {
        public G1DVX G1 { get; set; }
        public T1DVX T1 { get; set; }
    }
    [MessagePackObject(true)]

    public class G1DVX
    {
        public string iSIN { get; set; }
        public string symbol { get; set; }
        public string symbolSeqNum { get; set; }
        public string marketID { get; set; }
        public string marketIDSeqNum { get; set; }
        public string boardID { get; set; }
        public string boardIDSeqNum { get; set; }
        public string referencePrice { get; set; }
        public string referencePriceSeqNum { get; set; }
        public string ceilingPrice { get; set; }
        public string ceilingPriceSeqNum { get; set; }
        public string floorPrice { get; set; }
        public string floorPriceSeqNum { get; set; }
        public string bidCount { get; set; }
        public string bidCountSeqNum { get; set; }
        public string totalBidQtty { get; set; }
        public string totalBidQttySeqNum { get; set; }
        public string buyPriceX { get; set; }
        public string buyPriceXSeqNum { get; set; }
        public string buyQuantityX { get; set; }
        public string buyQuantityXSeqNum { get; set; }
        public string buyPrice9 { get; set; }
        public string buyPrice9SeqNum { get; set; }
        public string buyQuantity9 { get; set; }
        public string buyQuantity9SeqNum { get; set; }
        public string buyPrice8 { get; set; }
        public string buyPrice8SeqNum { get; set; }
        public string buyQuantity8 { get; set; }
        public string buyQuantity8SeqNum { get; set; }
        public string buyPrice7 { get; set; }
        public string buyPrice7SeqNum { get; set; }
        public string buyQuantity7 { get; set; }
        public string buyQuantity7SeqNum { get; set; }
        public string buyPrice6 { get; set; }
        public string buyQuantity6SeqNum { get; set; }
        public string buyPrice5 { get; set; }
        public string buyQuantity5SeqNum { get; set; }
        public string buyPrice4 { get; set; }
        public string buyQuantity4SeqNum { get; set; }
        public string buyPrice3 { get; set; }
        public string buyQuantity3SeqNum { get; set; }
        public string buyPrice2 { get; set; }
        public string buyQuantity2SeqNum { get; set; }
        public string buyPrice1 { get; set; }
        public string buyQuantity1SeqNum { get; set; }
        public string matchPrice { get; set; }
        public string matchPriceSeqNum { get; set; }
        public string matchQuantity { get; set; }
        public string matchQuantitySeqNum { get; set; }
        public string matchChange { get; set; }
        public string matchChangeSeqNum { get; set; }
        public string matchChangePercent { get; set; }
        public string matchChangePercentSeqNum { get; set; }
        public string totalNMQuantity { get; set; }
        public string totalNMQuantitySeqNum { get; set; }
        public string sellPrice1 { get; set; }
        public string sellPrice1SeqNum { get; set; }
        public string sellQuantity1 { get; set; }
        public string sellQuantity1SeqNum { get; set; }
        public string sellPrice2 { get; set; }
        public string sellPrice2SeqNum { get; set; }
        public string sellQuantity2 { get; set; }
        public string sellQuantity2SeqNum { get; set; }
        public string sellPrice3 { get; set; }
        public string sellPrice3SeqNum { get; set; }
        public string sellQuantity3 { get; set; }
        public string sellQuantity3SeqNum { get; set; }
        public string sellPrice4 { get; set; }
        public string sellPrice4SeqNum { get; set; }
        public string sellQuantity4 { get; set; }
        public string sellQuantity4SeqNum { get; set; }
        public string sellPrice5 { get; set; }
        public string sellPrice5SeqNum { get; set; }
        public string sellQuantity5 { get; set; }
        public string sellQuantity5SeqNum { get; set; }
        public string sellPrice6 { get; set; }
        public string sellPrice6SeqNum { get; set; }
        public string sellQuantity6 { get; set; }
        public string sellQuantity6SeqNum { get; set; }
        public string sellPrice7 { get; set; }
        public string sellPrice7SeqNum { get; set; }
        public string sellQuantity7 { get; set; }
        public string sellQuantity7SeqNum { get; set; }
        public string sellPrice8 { get; set; }
        public string sellPrice8SeqNum { get; set; }
        public string sellQuantity8 { get; set; }
        public string sellQuantity8SeqNum { get; set; }
        public string sellPrice9 { get; set; }
        public string sellPrice9SeqNum { get; set; }
        public string sellQuantity9 { get; set; }
        public string sellQuantity9SeqNum { get; set; }
        public string sellPriceX { get; set; }
        public string sellPriceXSeqNum { get; set; }
        public string sellQuantityX { get; set; }
        public string sellQuantityXSeqNum { get; set; }
        public string offerCount { get; set; }
        public string offerCountSeqNum { get; set; }
        public string totalOfferQtty { get; set; }
        public string totalOfferQttySeqNum { get; set; }
        public string openPrice { get; set; }
        public string openPriceSeqNum { get; set; }
        public string averagePrice { get; set; }
        public string averagePriceSeqNum { get; set; }
        public string highestPrice { get; set; }
        public string highestPriceSeqNum { get; set; }
        public string lowestPrice { get; set; }
        public string lowestPriceSeqNum { get; set; }
        public string foreignBuyQuantity { get; set; }
        public string foreignBuyQuantitySeqNum { get; set; }
        public string foreignSellQuantity { get; set; }
        public string foreignSellQuantitySeqNum { get; set; }
        public string foreignRoomRemain { get; set; }
        public string foreignRoomRemainSeqNum { get; set; }
        public string openInterest { get; set; }
        public string openInterestSeqNum { get; set; }
        public string lastTradingDate { get; set; }
        public string lastTradingDateSeqNum { get; set; }
        public string exClassTypeSeqNum { get; set; }
        public string symbolTradingMethodSeqNum { get; set; }
        public string symbolTradingSantionSeqNum { get; set; }
        public string tentativeExecutionPrice { get; set; }
        public string tentativeExecutionPriceSeqNum { get; set; }
        public string expectedTradePx { get; set; }
        public string expectedTradePxSeqNum { get; set; }
        public string expectedTradeQty { get; set; }
        public string expectedTradeQtySeqNum { get; set; }
        public string boardEvtIDSeqNum { get; set; }
        public string sessOpenCloseCodeSeqNum { get; set; }
        public string tradingSessionIDSeqNum { get; set; }
        public string transactTime { get; set; }
        public string transactTimeSeqNum { get; set; }
        public string td { get; set; }
        public string tradeDateSeqNum { get; set; }
    }
    [MessagePackObject(true)]

    public class T1DVX
    {
        public string iSIN { get; set; }
        public string symbol { get; set; }
        public string symbolSeqNum { get; set; }
        public string marketID { get; set; }
        public string marketIDSeqNum { get; set; }
        public string boardID { get; set; }
        public string boardIDSeqNum { get; set; }
        public string referencePrice{get; set;}
        public string referencePriceSeqNum { get; set; }
        public string ceilingPrice { get; set; }
        public string ceilingPriceSeqNum { get; set; }
        public string floorPrice { get; set; }
        public string floorPriceSeqNum { get; set; }
        public string bidCount { get; set; }
        public string bidCountSeqNum { get; set; }
        public string totalBidQtty { get; set; }
        public string totalBidQttySeqNum { get; set; }
        public string buyPriceX { get; set; }
        public string buyPriceXSeqNum { get; set; }
        public string buyQuantityX { get; set; }
        public string buyQuantityXSeqNum { get; set; }
        public string buyPrice9 { get; set; }
        public string buyPrice9SeqNum{get; set;}
        public string buyQuantity9 { get; set; }
        public string buyQuantity9SeqNum { get; set; }
        public string buyPrice8 { get; set; }
        public string buyPrice8SeqNum { get; set; }
        public string buyQuantity8 { get; set; }
        public string buyQuantity8SeqNum { get; set; }
        public string buyPrice7 { get; set; }
        public string buyPrice7SeqNum { get; set; }
        public string buyQuantity7 { get; set; }
        public string buyQuantity7SeqNum { get; set; }
        public string buyPrice6 { get; set; }
        public string buyQuantity6SeqNum { get; set; }
        public string buyPrice5 { get; set; }
        public string buyQuantity5SeqNum { get; set; }
        public string buyPrice4 { get; set; }
        public string buyQuantity4SeqNum { get; set; }
        public string buyPrice3 { get; set; }
        public string buyQuantity3SeqNum { get; set; }
        public string buyPrice2 { get; set; }
        public string buyQuantity2SeqNum { get; set; }
        public string buyPrice1 { get; set; }
        public string buyQuantity1SeqNum { get; set; }
        public string matchPrice { get; set; }
        public string matchPriceSeqNum { get; set; }
        public string matchQuantity { get; set; }
        public string matchQuantitySeqNum { get; set; }
        public string matchChange { get; set; }
        public string matchChangeSeqNum { get; set; }
        public string matchChangePercent { get; set; }
        public string matchChangePercentSeqNum { get; set; }
        public string totalNMQuantity { get; set; }
        public string totalNMQuantitySeqNum { get; set; }
        public string sellPrice1 { get; set; }
        public string sellPrice1SeqNum { get; set; }
        public string sellQuantity1 { get; set; }
        public string sellQuantity1SeqNum { get; set; }
        public string sellPrice2 { get; set; }
        public string sellPrice2SeqNum { get; set; }
        public string sellQuantity2 { get; set; }
        public string sellQuantity2SeqNum { get; set; }
        public string sellPrice3 { get; set; }
        public string sellPrice3SeqNum { get; set; }
        public string sellQuantity3 { get; set; }
        public string sellQuantity3SeqNum { get; set; }
        public string sellPrice4 { get; set; }
        public string sellPrice4SeqNum { get; set; }
        public string sellQuantity4 { get; set; }
        public string sellQuantity4SeqNum { get; set; }
        public string sellPrice5 { get; set; }
        public string sellPrice5SeqNum { get; set; }
        public string sellQuantity5 { get; set; }
        public string sellQuantity5SeqNum { get; set; }
        public string sellPrice6 { get; set; }
        public string sellPrice6SeqNum { get; set; }
        public string sellQuantity6 { get; set; }
        public string sellQuantity6SeqNum { get; set; }
        public string sellPrice7 { get; set; }
        public string sellPrice7SeqNum { get; set; }
        public string sellQuantity7 { get; set; }
        public string sellQuantity7SeqNum { get; set; }
        public string sellPrice8 { get; set; }
        public string sellPrice8SeqNum { get; set; }
        public string sellQuantity8 { get; set; }
        public string sellQuantity8SeqNum { get; set; }
        public string sellPrice9 { get; set; }
        public string sellPrice9SeqNum { get; set; }
        public string sellQuantity9 { get; set; }
        public string sellQuantity9SeqNum { get; set; }
        public string sellPriceX { get; set; }
        public string sellPriceXSeqNum { get; set; }
        public string sellQuantityX { get; set; }
        public string sellQuantityXSeqNum { get; set; }
        public string offerCount { get; set; }
        public string offerCountSeqNum { get; set; }
        public string totalOfferQtty { get; set; }
        public string totalOfferQttySeqNum{get; set;}
        public string openPrice { get; set; }
        public string openPriceSeqNum { get; set; }
        public string averagePrice { get; set; }
        public string averagePriceSeqNum { get; set; }
        public string highestPrice { get; set; }
        public string highestPriceSeqNum { get; set; }
        public string lowestPrice { get; set; }
        public string lowestPriceSeqNum { get; set; }
        public string foreignBuyQuantity { get; set; }
        public string foreignBuyQuantitySeqNum { get; set; }
        public string foreignSellQuantity { get; set; }
        public string foreignSellQuantitySeqNum { get; set; }
        public string foreignRoomRemain { get; set; }
        public string foreignRoomRemainSeqNum { get; set; }
        public string openInterest { get; set; }
        public string openInterestSeqNum { get; set; }
        public string lastTradingDate { get; set; }
        public string lastTradingDateSeqNum { get; set; }
        public string exClassTypeSeqNum { get; set; }
        public string symbolTradingMethodSeqNum { get; set; }
        public string symbolTradingSantionSeqNum { get; set; }
        public string tentativeExecutionPrice { get; set; }
        public string tentativeExecutionPriceSeqNum { get; set; }
        public string expectedTradePx{get; set;}
        public string expectedTradePxSeqNum { get; set; }
        public string expectedTradeQty { get; set; }
        public string expectedTradeQtySeqNum { get; set; }
        public string boardEvtIDSeqNum { get; set; }
        public string sessOpenCloseCodeSeqNum { get; set; }
        public string tradingSessionIDSeqNum { get; set; }
        public string transactTime { get; set; }
        public string transactTimeSeqNum { get; set; }
        public string td { get; set; }
        public string tradeDateSeqNum { get; set; }
    }
}
